### ISSUE TITLE
DRM Issue

### ISSUE THREAD

**Issue by WifiRouterYT** [4mitabh/Ideapad_S340#2]
Hi!

I used your prebuilt EFI to install Mac OS Ventura on my Lenovo S340-15IWL (touch). I updated a few kexts and I believe I removed some spoofed CPU data from config.plist, and now my DRM is broken. I'm unable to even stream music! at least YouTube still works I guess. Anyway, I have the i3 version of the laptop, and the reason for removing the CPU spoof stuff from config.plist was because it showed up as an i7 and I thought it was just wrong. It worked fine until I messed with the config.plist. Perhaps you know the correct settings? I've attached the EFI below (through link because funny GitHub upload limit), works perfectly except, well, DRM.

another issue I had that isn't as big and bearable is when I'm trying to drag, say a file, over a long distance on the screen, when I pick up my finger and put it on another spot of the trackpad the cursor snaps back and I lose progress on the move. not sure how to explain.

thanks in advance.

efi: https://file.io/ulUy7mRdpoA5

**Comment by 4mitabh** [comment]
You may check this part of the guide for the DRM issue : https://dortania.github.io/OpenCore-Post-Install/universal/drm.html#testing-hardware-acceleration-and-decoding

I know, the drag-and-drop you are talking of... I havent been able to find a solution to it. 
Honestly - I havent tried hard enough to find a solution because I use an external mouse.

**Comment by aruhant** [comment]
Closing stale issues
